server:
  port: 8566
spring:
  application:
    name: RabbitMQ DLX
  #  RabbitMQ配置
  rabbitmq:
    host: 192.168.0.182
    port: 5672
    username: guest
    password: guest
    # 虚拟主机
    virtual-host: /
    # 消息投递 确认属性配置
    # NONE值是禁用发布确认模式，是默认值
    # CORRELATED值是发布消息成功到交换器后会触发回调方法
    # SIMPLE值经测试有两种效果：
    #   其一效果和CORRELATED值一样会触发回调方法；
    #   其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，根据返回结果来判定下一步的逻辑
    #   要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker;
    publisher-confirm-type: CORRELATED
    # 可以确保消息在未被队列接收时返回
    publisher-returns: true
    template:
      # 设置交换机处理失败消息的模式
      mandatory: true
    listener:
      # 设置消费端手动确认消息 ack
      simple:
        acknowledge-mode: manual
        # prefetch限流机制  后面跟上每次取到的消息数量 再手动确认之后 才会去拉去mq中剩余的消息
        prefetch: 1
      direct:
        acknowledge-mode: manual
        # prefetch限流机制
        prefetch: 1
